# Generated by Django 5.1.2 on 2024-11-14 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_account", "0001_initial"),
        ("core", "0002_user_image_height_user_image_width_alter_user_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AppearanceSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("theme-rose", "Rose"),
                            ("theme-blue", "Blue"),
                            ("theme-green", "Green"),
                            ("theme-dark", "Dark Mode"),
                            ("theme-contrast", "High Contrast"),
                        ],
                        default="theme-rose",
                        max_length=255,
                        verbose_name="Theme color",
                    ),
                ),
                (
                    "font",
                    models.CharField(
                        choices=[
                            ("font-sans", "Sans-Serif"),
                            ("font-serif", "Serif"),
                            ("font-mono", "Monospace"),
                            ("font-comic", "Comic"),
                        ],
                        default="font-sans",
                        max_length=255,
                        verbose_name="Theme font",
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("size-xs", "Extra Small"),
                            ("size-sm", "Small"),
                            ("size-base", "Default"),
                            ("size-lg", "Large"),
                        ],
                        default="size-base",
                        max_length=255,
                        verbose_name="Theme size",
                    ),
                ),
                (
                    "background",
                    models.CharField(
                        choices=[
                            ("NONE", "None"),
                            ("CLOUDS", "Clouds"),
                            ("CHARLIE", "Charlie Brown"),
                            ("WAVES", "Waves"),
                        ],
                        default="NONE",
                        max_length=255,
                        verbose_name="Theme background",
                    ),
                ),
                (
                    "logo",
                    models.CharField(
                        choices=[
                            ("SIMPLE", "Simple"),
                            ("PRIDE", "Pride"),
                            ("EYE", "All-Seeing Eye"),
                        ],
                        default="SIMPLE",
                        max_length=255,
                        verbose_name="Theme logo",
                    ),
                ),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appearance_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RunSQL(
            """
            INSERT INTO account_appearancesettings (
                owner_id,
                color,
                font,
                size,
                background,
                logo
            )
            SELECT
                id AS owner_id,
                appearance_color AS color,
                appearance_font AS font,
                appearance_size AS size,
                appearance_background AS background,
                appearance_logo AS logo
            FROM
                core_user
            """,
            reverse_sql="""
                INSERT INTO core_user (
                    appearance_color,
                    appearance_font,
                    appearance_size,
                    appearance_background,
                    appearance_logo
                ) SELECT
                    color AS appearance_color,
                    font AS appearance_font,
                    size AS appearance_size,
                    background AS appearance_background,
                    logo AS appearance_logo
                FROM
                    account_appearancesettings
                WHERE
                    core_user.id = account_appearancesettings.owner_id
            """,
        ),
    ]
