# Generated by Django 5.1.2 on 2024-11-14 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_account', '0002_appearancesettings'),
        ("core", "0004_alter_user_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_see_profile', models.CharField(choices=[('E', 'Everyone logged in'), ('F', 'Only my friends')], default='F', max_length=1, verbose_name='Who can see your page?')),
                ('can_send_messages', models.CharField(choices=[('E', 'Everyone logged in'), ('F', 'Only my friends')], default='F', max_length=1, verbose_name='Who can send you messages?')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunSQL(
            """
            INSERT INTO account_privacysettings (
                owner_id,
                can_see_profile,
                can_send_messages
            )
            SELECT
                id AS owner_id,
                can_see_profile,
                can_send_messages
            FROM
                core_user
            """,
            reverse_sql="""
                INSERT INTO core_user (
                    can_see_profile,
                    can_send_messages
                ) SELECT
                    can_see_profile,
                    can_send_messages
                FROM
                    account_privacysettings
                WHERE
                    core_user.id = account_privacysettings.owner_id
            """,
        ),
    ]
