# Generated by Django 5.1.2 on 2024-11-17 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_account', '0004_alter_appearancesettings_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsettings',
            name='on_new_greeting',
            field=models.BooleanField(default=True, verbose_name='On new greetings'),
        ),
    ]
