# Generated by Django 5.1.2 on 2024-11-14 21:08

import annoying.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_privacysettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='appearancesettings',
            name='owner',
            field=annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appearance_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='owner',
            field=annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='privacysettings',
            name='owner',
            field=annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_settings', to=settings.AUTH_USER_MODEL),
        ),
    ]
