# Generated by Django 5.1.2 on 2024-10-23 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Birthday'),
        ),
        migrations.AddField(
            model_name='user',
            name='favourite_books',
            field=models.TextField(blank=True, null=True, verbose_name='Favourite books'),
        ),
        migrations.AddField(
            model_name='user',
            name='favourite_food',
            field=models.TextField(blank=True, null=True, verbose_name='Favourite food'),
        ),
        migrations.AddField(
            model_name='user',
            name='favourite_movies',
            field=models.TextField(blank=True, null=True, verbose_name='Favourite movies'),
        ),
        migrations.AddField(
            model_name='user',
            name='favourite_music',
            field=models.TextField(blank=True, null=True, verbose_name='Favourite music'),
        ),
        migrations.AddField(
            model_name='user',
            name='hobbies',
            field=models.TextField(blank=True, null=True, verbose_name='Hobbies'),
        ),
        migrations.AddField(
            model_name='user',
            name='i_am_good_at',
            field=models.TextField(blank=True, null=True, verbose_name='I am good at'),
        ),
        migrations.AddField(
            model_name='user',
            name='i_wish_for',
            field=models.TextField(blank=True, null=True, verbose_name='I wish for'),
        ),
        migrations.AddField(
            model_name='user',
            name='looking_for',
            field=models.TextField(blank=True, null=True, verbose_name='Looking for'),
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nickname'),
        ),
        migrations.AddField(
            model_name='user',
            name='pronouns',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Pronouns'),
        ),
        migrations.AddField(
            model_name='user',
            name='relationship',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Relationship'),
        ),
        migrations.AddField(
            model_name='user',
            name='what_i_dont_like',
            field=models.TextField(blank=True, null=True, verbose_name="What I don't like"),
        ),
        migrations.AddField(
            model_name='user',
            name='what_i_like',
            field=models.TextField(blank=True, null=True, verbose_name='What I like'),
        ),
    ]
