# Generated by Django 5.1.2 on 2024-11-12 15:21

import core.helpers
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, height_field='image_height', null=True, upload_to=core.helpers.UploadToUuidFilename('profiles/'), validators=[core.helpers.ValidateMaxFilesize(10)], verbose_name='Profile picture', width_field='image_width'),
        ),
    ]
