# Generated by Django 5.1.2 on 2024-10-23 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_birthday_user_favourite_books_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='profiles/', verbose_name='Profile picture'),
        ),
    ]
