# Generated by Django 5.1.2 on 2024-11-14 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_user_image_height_user_image_width_alter_user_image"),
        ("my_account", "0002_appearancesettings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="appearance_background",
        ),
        migrations.RemoveField(
            model_name="user",
            name="appearance_color",
        ),
        migrations.RemoveField(
            model_name="user",
            name="appearance_font",
        ),
        migrations.RemoveField(
            model_name="user",
            name="appearance_logo",
        ),
        migrations.RemoveField(
            model_name="user",
            name="appearance_size",
        ),
    ]
