# Generated by Django 5.1.2 on 2024-11-14 20:19

import core.helpers
import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_user_appearance_background_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, height_field='image_height', null=True, upload_to=core.helpers.UploadToUuidFilename('profiles/'), validators=[core.helpers.ValidateMaxFilesize(10), core.helpers.ValidateImageSize(100, 100, 4000, 4000), core.helpers.ValidateImageAspectRatio(0.5, 1.8)], verbose_name='Profile picture', width_field='image_width'),
        ),
    ]
