# Generated by Django 5.1.2 on 2024-10-24 09:51

import pictures.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image_height',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='image_width',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=pictures.models.PictureField(aspect_ratios=[None], blank=True, breakpoints={'lg': 1024, 'md': 768}, container_width=1024, file_types=['WEBP'], grid_columns=12, height_field='image_height', null=True, pixel_densities=[1, 2], upload_to='profiles/', verbose_name='Profile picture', width_field='image_width'),
        ),
    ]
