# Generated by Django 5.1.2 on 2024-11-15 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_user_can_see_profile_and_more'),
        ('my_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='user',
            name='favourite_books',
        ),
        migrations.RemoveField(
            model_name='user',
            name='favourite_food',
        ),
        migrations.RemoveField(
            model_name='user',
            name='favourite_movies',
        ),
        migrations.RemoveField(
            model_name='user',
            name='favourite_music',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_car_make',
        ),
        migrations.RemoveField(
            model_name='user',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='grew_up_street',
        ),
        migrations.RemoveField(
            model_name='user',
            name='hobbies',
        ),
        migrations.RemoveField(
            model_name='user',
            name='i_am_good_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='i_wish_for',
        ),
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
        migrations.RemoveField(
            model_name='user',
            name='image_height',
        ),
        migrations.RemoveField(
            model_name='user',
            name='image_width',
        ),
        migrations.RemoveField(
            model_name='user',
            name='looking_for',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mothers_maiden_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name_of_first_pet',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nickname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pronouns',
        ),
        migrations.RemoveField(
            model_name='user',
            name='relationship',
        ),
        migrations.RemoveField(
            model_name='user',
            name='what_i_dont_like',
        ),
        migrations.RemoveField(
            model_name='user',
            name='what_i_like',
        ),
    ]
