# Generated by Django 5.1.2 on 2024-11-11 17:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PinboardMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField(blank=True, null=True, verbose_name='Pinboard Message')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('created_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pinboard', to=settings.AUTH_USER_MODEL, verbose_name='Created for')),
            ],
            options={
                'verbose_name': 'Pinboard Message',
                'verbose_name_plural': 'Pinboard Messages',
            },
        ),
    ]
