emoticons = [
    "antifa",
    "arrow",
    "biggrin",
    "confused",
    "cool",
    "cry",
    "eek",
    "evil",
    "exclaim",
    "geek",
    "idea",
    "lol",
    "mad",
    "mrgreen",
    "neutral",
    "question",
    "razz",
    "redface",
    "rolleyes",
    "sad",
    "secco",
    "smile",
    "surprised",
    "twisted",
    "ugeek",
    "wink",
]

emoticons = [(f":{s}:", f"emoticons/icon_{s}.gif") for s in emoticons]
