apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "geheimvz.fullname" . }}-database-config
  labels:
    {{- include "geheimvz.labels" . | nindent 4 }}
data:
  db_settings.py: |-
    from .settings import *
    import os
    import environ

    env = environ.Env()
    DATABASES = {
      "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": {{ .Values.config.DATABASE_NAME | quote }},
        "USER": {{ .Values.config.DATABASE_USER  | default "postgres" | quote  }},
        "PASSWORD": env("DATABASE_PASSWORD"),
        "HOST": {{ .Values.config.DATABASE_HOST | default "geheimvz-postgresql" | quote  }},
        "PORT": {{ .Values.config.DATABASE_PORT | default "5432" | quote }},
      }
    }
