# Generated by Django 5.1.2 on 2024-11-18 12:38

import core.helpers
import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_group_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, height_field='image_height', null=True, upload_to=core.helpers.UploadToUuidFilename('groups/'), validators=[core.helpers.ValidateMaxFilesize(10), core.helpers.ValidateImageSize(100, 100, 10000, 10000), core.helpers.ValidateImageAspectRatio(0.5, 1.8)], verbose_name='Group picture', width_field='image_width'),
        ),
    ]
