# Generated by Django 5.1.3 on 2024-12-13 12:39

import core.helpers
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_alter_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='attachment',
            field=imagekit.models.fields.ProcessedImageField(blank=True, height_field='attachment_height', null=True, upload_to=core.helpers.UploadToUuidFilename('groups/attachments/'), validators=[core.helpers.ValidateMaxFilesize(10), core.helpers.ValidateImageSize(100, 100, 10000, 10000), core.helpers.ValidateImageAspectRatio(0.5, 1.8)], verbose_name='Attachment', width_field='attachment_width'),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='attachment_height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='attachment_width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
