# Generated by Django 5.1.2 on 2024-11-15 13:46

import annoying.fields
import core.helpers
import django.db.models.deletion
import imagekit.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_remove_user_can_see_profile_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_height', models.PositiveIntegerField(blank=True, null=True)),
                ('image_width', models.PositiveIntegerField(blank=True, null=True)),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, height_field='image_height', null=True, upload_to=core.helpers.UploadToUuidFilename('profiles/'), validators=[core.helpers.ValidateMaxFilesize(10), core.helpers.ValidateImageSize(100, 100, 4000, 4000), core.helpers.ValidateImageAspectRatio(0.5, 1.8)], verbose_name='Profile picture', width_field='image_width')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Full name')),
                ('nickname', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nickname')),
                ('pronouns', models.CharField(blank=True, max_length=255, null=True, verbose_name='Pronouns')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Birthday')),
                ('mothers_maiden_name', models.CharField(blank=True, max_length=255, null=True, verbose_name="Your mother's maiden name")),
                ('name_of_first_pet', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name of your first pet')),
                ('grew_up_street', models.CharField(blank=True, max_length=255, null=True, verbose_name='Street where you grew up')),
                ('first_car_make', models.CharField(blank=True, max_length=255, null=True, verbose_name='Make of your first car')),
                ('looking_for', models.TextField(blank=True, null=True, verbose_name='Looking for')),
                ('relationship', models.CharField(blank=True, max_length=255, null=True, verbose_name='Relationship')),
                ('hobbies', models.TextField(blank=True, null=True, verbose_name='Hobbies')),
                ('what_i_like', models.TextField(blank=True, null=True, verbose_name='What I like')),
                ('what_i_dont_like', models.TextField(blank=True, null=True, verbose_name="What I don't like")),
                ('favourite_music', models.TextField(blank=True, null=True, verbose_name='Favourite music')),
                ('favourite_movies', models.TextField(blank=True, null=True, verbose_name='Favourite movies')),
                ('favourite_books', models.TextField(blank=True, null=True, verbose_name='Favourite books')),
                ('favourite_food', models.TextField(blank=True, null=True, verbose_name='Favourite food')),
                ('i_am_good_at', models.TextField(blank=True, null=True, verbose_name='I am good at')),
                ('i_wish_for', models.TextField(blank=True, null=True, verbose_name='I wish for')),
                ('owner', annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunSQL(
            """
            INSERT INTO my_profile_myprofile (
                owner_id,
                image_height,
                image_width,
                image,
                full_name,
                nickname,
                pronouns,
                birthday,
                mothers_maiden_name,
                name_of_first_pet,
                grew_up_street,
                first_car_make,
                looking_for,
                relationship,
                hobbies,
                what_i_like,
                what_i_dont_like,
                favourite_music,
                favourite_movies,
                favourite_books,
                favourite_food,
                i_am_good_at,
                i_wish_for
            )
            SELECT
                id AS owner_id,
                image_height,
                image_width,
                image,
                full_name,
                nickname,
                pronouns,
                birthday,
                mothers_maiden_name,
                name_of_first_pet,
                grew_up_street,
                first_car_make,
                looking_for,
                relationship,
                hobbies,
                what_i_like,
                what_i_dont_like,
                favourite_music,
                favourite_movies,
                favourite_books,
                favourite_food,
                i_am_good_at,
                i_wish_for
            FROM
                core_user
            """,
            reverse_sql="""
                INSERT INTO core_user (
                    image_height,
                    image_width,
                    image,
                    full_name,
                    nickname,
                    pronouns,
                    birthday,
                    mothers_maiden_name,
                    name_of_first_pet,
                    grew_up_street,
                    first_car_make,
                    looking_for,
                    relationship,
                    hobbies,
                    what_i_like,
                    what_i_dont_like,
                    favourite_music,
                    favourite_movies,
                    favourite_books,
                    favourite_food,
                    i_am_good_at,
                    i_wish_for
                ) SELECT
                    image_height,
                    image_width,
                    image,
                    full_name,
                    nickname,
                    pronouns,
                    birthday,
                    mothers_maiden_name,
                    name_of_first_pet,
                    grew_up_street,
                    first_car_make,
                    looking_for,
                    relationship,
                    hobbies,
                    what_i_like,
                    what_i_dont_like,
                    favourite_music,
                    favourite_movies,
                    favourite_books,
                    favourite_food,
                    i_am_good_at,
                    i_wish_for
                FROM
                    my_profile_myprofile
                WHERE
                    core_user.id = my_profile_myprofile.owner_id
            """,
        ),
    ]
