# Generated by Django 5.1.2 on 2024-11-16 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='myprofile',
            name='greeting_word',
            field=models.CharField(choices=[('GRUSCHELN', 'Gruscheln'), ('NUDGE', 'Nudge'), ('MEOW', 'Meow'), ('WAVE', 'Wave')], default='GRUSCHELN', max_length=255, verbose_name='Greeting word'),
        ),
        migrations.CreateModel(
            name='Greeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='greetings_sent', to=settings.AUTH_USER_MODEL, verbose_name='Sender')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='greetings_received', to=settings.AUTH_USER_MODEL, verbose_name='Recipient')),
            ],
            options={
                'verbose_name': 'Greeting',
                'verbose_name_plural': 'Greetings',
            },
        ),
    ]
